<script setup>
import DefaultLayout from '@/Layouts/DefaultLayout.vue';
import { Head, useForm, router } from '@inertiajs/vue3';
import { ref } from 'vue';
import Modal from '@/Components/Modal.vue';
import InputLabel from '@/Components/InputLabel.vue';
import TextInput from '@/Components/TextInput.vue';
import PrimaryButton from '@/Components/PrimaryButton.vue';
import SecondaryButton from '@/Components/SecondaryButton.vue';
import DangerButton from '@/Components/DangerButton.vue';

const props = defineProps({
    versions: Array,
    academicYears: Array,
    currentAcademicYearId: Number,
});

const showGenerateModal = ref(false);
const showDeleteModal = ref(false);
const deletingVersion = ref(null);

const form = useForm({
    academic_year_id: props.currentAcademicYearId,
    version_name: '',
    description: '',
});

const openGenerateModal = () => {
    form.reset();
    form.academic_year_id = props.currentAcademicYearId;
    form.version_name = `Draft v${props.versions.length + 1} - ${new Date().toLocaleDateString()}`;
    showGenerateModal.value = true;
};

const generateTimetable = () => {
    form.post(route('timetable.generate.store'), {
        onSuccess: () => {
            showGenerateModal.value = false;
            form.reset();
        },
    });
};

const publishVersion = (version) => {
    if (confirm('Are you sure you want to publish this version? It will become visible to all users.')) {
        router.post(route('timetable.versions.publish', version.id));
    }
};

const confirmDelete = (version) => {
    deletingVersion.value = version;
    showDeleteModal.value = true;
};

const deleteVersion = () => {
    router.delete(route('timetable.versions.destroy', deletingVersion.value.id), {
        onSuccess: () => {
            showDeleteModal.value = false;
        },
    });
};

const onAcademicYearChange = (e) => {
    router.get(route('timetable.generate.index'), { academic_year_id: e.target.value });
};

const getCoveragePercentage = (stats) => {
    if (!stats || !stats.total_allocations) return 0;
    return Math.round((stats.scheduled / stats.total_allocations) * 100);
};
</script>

<template>
    <Head title="Generate Timetable" />

    <DefaultLayout>
        <template #header>
            <div class="flex justify-between items-center">
                <h2 class="font-semibold text-xl text-gray-800 leading-tight">Timetable Generation</h2>
                <div class="flex items-center gap-4">
                    <select 
                        :value="currentAcademicYearId" 
                        @change="onAcademicYearChange"
                        class="border-gray-300 focus:border-indigo-500 focus:ring-indigo-500 rounded-md shadow-sm"
                    >
                        <option v-for="year in academicYears" :key="year.id" :value="year.id">
                            {{ year.name }}
                        </option>
                    </select>
                    <PrimaryButton @click="openGenerateModal">
                        <i class="fas fa-magic mr-2"></i> Generate New
                    </PrimaryButton>
                </div>
            </div>
        </template>

        <div class="py-12">
            <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
                
                <div v-if="versions.length === 0" class="text-center py-20 bg-white rounded-lg shadow">
                    <i class="fas fa-calendar-alt text-6xl text-gray-300 mb-4"></i>
                    <h3 class="text-xl font-medium text-gray-900">No Timetables Generated</h3>
                    <p class="text-gray-500 mt-2">Click "Generate New" to create your first timetable.</p>
                </div>

                <div v-else class="space-y-6">
                    <div v-for="version in versions" :key="version.id" class="bg-white overflow-hidden shadow-sm sm:rounded-lg p-6 border-l-4" :class="version.is_active ? 'border-green-500' : 'border-gray-300'">
                        <div class="flex justify-between items-start">
                            <div>
                                <div class="flex items-center gap-3">
                                    <h3 class="text-lg font-bold text-gray-900">{{ version.version_name }}</h3>
                                    <span v-if="version.is_active" class="bg-green-100 text-green-800 text-xs px-2 py-1 rounded-full font-semibold">ACTIVE</span>
                                    <span v-if="version.is_published" class="bg-blue-100 text-blue-800 text-xs px-2 py-1 rounded-full font-semibold">PUBLISHED</span>
                                </div>
                                <p class="text-gray-500 text-sm mt-1">{{ version.description || 'No description' }}</p>
                                <div class="text-xs text-gray-400 mt-2">
                                    Generated by {{ version.creator?.name }} on {{ new Date(version.created_at).toLocaleString() }}
                                </div>
                            </div>
                            
                            <div class="flex gap-2">
                                <a :href="route('timetable.view.class')" class="inline-flex items-center px-4 py-2 bg-gray-800 border border-transparent rounded-md font-semibold text-xs text-white uppercase tracking-widest hover:bg-gray-700">
                                    <i class="fas fa-eye mr-2"></i> View
                                </a>
                                <button v-if="!version.is_published" @click="publishVersion(version)" class="inline-flex items-center px-4 py-2 bg-indigo-600 border border-transparent rounded-md font-semibold text-xs text-white uppercase tracking-widest hover:bg-indigo-500">
                                    <i class="fas fa-check mr-2"></i> Publish
                                </button>
                                <button @click="confirmDelete(version)" class="text-red-500 hover:text-red-700 p-2">
                                    <i class="fas fa-trash"></i>
                                </button>
                            </div>
                        </div>

                        <!-- Stats -->
                        <div class="mt-6 grid grid-cols-1 md:grid-cols-3 gap-4 border-t pt-4">
                            <div class="bg-gray-50 p-3 rounded">
                                <div class="text-xs text-gray-500 uppercase">Coverage</div>
                                <div class="text-xl font-bold" :class="getCoveragePercentage(version.generation_stats) === 100 ? 'text-green-600' : 'text-yellow-600'">
                                    {{ getCoveragePercentage(version.generation_stats) }}%
                                </div>
                                <div class="text-xs text-gray-400">
                                    {{ version.generation_stats?.scheduled }} / {{ version.generation_stats?.total_allocations }} slots
                                </div>
                            </div>
                            
                            <div class="bg-gray-50 p-3 rounded">
                                <div class="text-xs text-gray-500 uppercase">Conflicts</div>
                                <div class="text-xl font-bold text-red-600">
                                    {{ version.generation_stats?.failed || 0 }}
                                </div>
                                <div class="text-xs text-gray-400">Unscheduled allocations</div>
                            </div>

                            <div class="bg-gray-50 p-3 rounded">
                                <div class="text-xs text-gray-500 uppercase">Status</div>
                                <div class="text-sm font-medium mt-1">
                                    {{ version.is_active ? 'Live Timetable' : 'Draft Version' }}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>

        <!-- Generate Modal -->
        <Modal :show="showGenerateModal" @close="showGenerateModal = false">
            <div class="p-6">
                <h2 class="text-lg font-medium text-gray-900 mb-4">Generate Timetable</h2>
                <p class="text-sm text-gray-500 mb-4">
                    This will run the automated scheduling algorithm based on your configured periods, allocations, and constraints.
                </p>
                
                <div class="space-y-4">
                    <div>
                        <InputLabel for="version_name" value="Version Name" />
                        <TextInput id="version_name" v-model="form.version_name" type="text" class="mt-1 block w-full" />
                    </div>

                    <div>
                        <InputLabel for="description" value="Description (Optional)" />
                        <TextInput id="description" v-model="form.description" type="text" class="mt-1 block w-full" placeholder="e.g. Draft for Term 1" />
                    </div>
                </div>

                <div class="mt-6 flex justify-end gap-3">
                    <SecondaryButton @click="showGenerateModal = false">Cancel</SecondaryButton>
                    <PrimaryButton @click="generateTimetable" :disabled="form.processing">
                        <i class="fas fa-cogs mr-2"></i> Run Generator
                    </PrimaryButton>
                </div>
            </div>
        </Modal>

        <!-- Delete Modal -->
        <Modal :show="showDeleteModal" @close="showDeleteModal = false">
            <div class="p-6">
                <h2 class="text-lg font-medium text-gray-900 mb-4">Delete Version</h2>
                <p class="text-gray-600 mb-6">
                    Are you sure you want to delete <strong>{{ deletingVersion?.version_name }}</strong>? This will remove all generated schedules for this version.
                </p>
                <div class="flex justify-end gap-3">
                    <SecondaryButton @click="showDeleteModal = false">Cancel</SecondaryButton>
                    <DangerButton @click="deleteVersion">Delete Version</DangerButton>
                </div>
            </div>
        </Modal>

    </DefaultLayout>
</template>
