<!DOCTYPE html>
<html>

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>Promotion Report</title>
    <style>
        body {
            font-family: 'DejaVu Sans', sans-serif;
            font-size: 12px;
            color: #333;
        }

        .header {
            text-align: center;
            margin-bottom: 20px;
            border-bottom: 2px solid #444;
            padding-bottom: 10px;
        }

        .logo {
            max-width: 100px;
            max-height: 100px;
            margin-bottom: 10px;
        }

        .institution-name {
            font-size: 20px;
            font-weight: bold;
            text-transform: uppercase;
            margin: 5px 0;
        }

        .report-title {
            font-size: 16px;
            font-weight: bold;
            margin: 10px 0;
            text-transform: uppercase;
            color: #555;
        }

        .meta-info {
            margin-bottom: 20px;
            width: 100%;
        }

        .meta-info td {
            padding: 5px;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }

        th,
        td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }

        th {
            background-color: #f2f2f2;
            font-weight: bold;
            text-transform: uppercase;
            font-size: 11px;
        }

        tr:nth-child(even) {
            background-color: #f9f9f9;
        }

        .footer {
            position: fixed;
            bottom: 0;
            width: 100%;
            text-align: center;
            font-size: 10px;
            color: #777;
            border-top: 1px solid #ddd;
            padding-top: 5px;
        }

        .badge {
            padding: 2px 5px;
            border-radius: 3px;
            font-size: 10px;
            color: white;
        }

        .badge-warning {
            background-color: #ffc107;
            color: #000;
        }

        .badge-success {
            background-color: #28a745;
        }

        .group-header {
            background-color: #e9ecef;
            font-weight: bold;
            padding: 10px;
            margin-top: 15px;
            border: 1px solid #ddd;
        }
    </style>
</head>

<body>
    <div class="header">
        @if($logoBase64)
        <img src="{{ $logoBase64 }}" class="logo" alt="Logo">
        @endif
        <div class="institution-name">{{ $institution->name ?? 'School Management System' }}</div>
        <div>{{ $institution->address ?? '' }}</div>
        <div>{{ $institution->email ?? '' }} | {{ $institution->phone ?? '' }}</div>
        <div class="report-title">Student Promotion Report</div>
    </div>

    <table class="meta-info">
        <tr>
            <td><strong>Academic Year:</strong> {{ $filters['academic_year'] }}</td>
            <td><strong>Class Filter:</strong> {{ $filters['from_class'] }}</td>
            <td><strong>Date Range:</strong> {{ $filters['date_range'] }}</td>
        </tr>
        <tr>
            <td><strong>Generated By:</strong> {{ $user }}</td>
            <td><strong>Generated At:</strong> {{ $generatedAt }}</td>
            <td><strong>Total Records:</strong> {{ $promotions->count() }}</td>
        </tr>
    </table>

    @if($promotions->isEmpty())
    <div style="text-align: center; padding: 20px; color: #777;">
        No promotion records found for the selected criteria.
    </div>
    @else
    @foreach($groupedPromotions as $groupName => $groupPromotions)
    <div class="group-header">
        Promotion Path: {{ $groupName }} ({{ $groupPromotions->count() }} students)
    </div>
    <table>
        <thead>
            <tr>
                <th style="width: 5%">#</th>
                <th style="width: 15%">Date</th>
                <th style="width: 15%">Adm No</th>
                <th style="width: 25%">Student Name</th>
                <th style="width: 15%">Type</th>
                <th style="width: 25%">Promoted By</th>
            </tr>
        </thead>
        <tbody>
            @foreach($groupPromotions as $index => $promotion)
            <tr>
                <td>{{ $index + 1 }}</td>
                <td>{{ $promotion->promoted_at->format('Y-m-d') }}</td>
                <td>{{ $promotion->student->admission_number ?? '-' }}</td>
                <td>{{ $promotion->student->name ?? '-' }}</td>
                <td>
                    @if($promotion->special_promotion)
                    <span class="badge badge-warning">Special</span>
                    @else
                    <span class="badge badge-success">Regular</span>
                    @endif
                </td>
                <td>{{ $promotion->promotedBy->name ?? 'System' }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>
    @endforeach
    @endif

    <div class="footer">
        Page <span class="page-number"></span>
        &copy; {{ date('Y') }} {{ $institution->name ?? 'School Management System' }}. All rights reserved.
    </div>

    <script type="text/php">
        if (isset($pdf)) {
            $pdf->page_script('
                $font = $fontMetrics->get_font("DejaVu Sans", "normal");
                $pdf->text(520, 820, "Page " . $PAGE_NUM . " of " . $PAGE_COUNT, $font, 10);
            ');
        }
    </script>
</body>

</html>