<!DOCTYPE html>
<html>

<head>
    <title>All Staff Report</title>
    <style>
        body {
            font-family: sans-serif;
            font-size: 12px;
        }

        .header {
            text-align: center;
            margin-bottom: 20px;
        }

        .header h1 {
            margin: 0;
            font-size: 18px;
            text-transform: uppercase;
        }

        .header h2 {
            margin: 5px 0;
            font-size: 14px;
        }

        .meta {
            margin-bottom: 15px;
            border-bottom: 1px solid #ccc;
            padding-bottom: 10px;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 10px;
        }

        th,
        td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }

        th {
            background-color: #f2f2f2;
            font-weight: bold;
        }

        .footer {
            position: fixed;
            bottom: 0;
            width: 100%;
            text-align: center;
            font-size: 10px;
            color: #666;
        }
    </style>
</head>

<body>
    <div class="header">
        <h1>ALBASAM COMPREHENSIVE SCHOOL</h1>
        <h2>All Staff Report</h2>
    </div>

    <div class="meta">
        <strong>Role Filter:</strong> {{ $roleName }} <br>
        <strong>Total Staff:</strong> {{ $employees->count() }} <br>
        <strong>Generated At:</strong> {{ $generated_at }}
    </div>

    <table>
        <thead>
            <tr>
                <th>Staff No.</th>
                <th>Name</th>
                <th>Roles</th>
                <th>Email</th>
                <th>Phone</th>
                <th>Joined Date</th>
            </tr>
        </thead>
        <tbody>
            @foreach($employees as $employee)
            <tr>
                <td>{{ $employee->employee_number ?? '-' }}</td>
                <td>{{ $employee->first_name }} {{ $employee->last_name }}</td>
                <td>
                    @if($employee->user && $employee->user->roles)
                    @foreach($employee->user->roles as $role)
                    {{ $role->display_name }}@if(!$loop->last), @endif
                    @endforeach
                    @else
                    -
                    @endif
                </td>
                <td>{{ $employee->email }}</td>
                <td>{{ $employee->primary_phone ?? '-' }}</td>
                <td>{{ $employee->date_of_hire ? \Carbon\Carbon::parse($employee->date_of_hire)->format('d/m/Y') : '-' }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        Generated by School Management System
    </div>
</body>

</html>